use serde::{Deserialize, Serialize};

use crate::id::SessionId;
use crate::principal::PlatformIdentity;
use crate::trust::TrustZone;

/// Where an action originated. Carried through the entire request lifecycle
/// and logged in the audit trail.
///
/// The policy engine maps `ActionOrigin` → `Principal` → permissions.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ActionOrigin {
    /// Direct CLI invocation on the host machine.
    LocalCli,

    /// Message from Telegram bridge.
    BridgeTelegram { user_id: String },

    /// Message from Slack bridge.
    BridgeSlack { user_id: String, channel_id: String },

    /// Generated by an agent session (via MCP tool call or parsed signal).
    AgentGenerated { session_id: SessionId },

    /// System heartbeat or scheduled task.
    SystemHeartbeat,

    /// A human explicitly approved this action. Wraps the original origin
    /// so the full provenance chain is preserved.
    HumanApproved {
        approver: String,
        original_origin: Box<ActionOrigin>,
    },
}

impl ActionOrigin {
    /// The trust zone this origin enters the system at.
    #[must_use]
    pub fn trust_zone(&self) -> TrustZone {
        match self {
            Self::BridgeTelegram { .. } | Self::BridgeSlack { .. } => TrustZone::Ingress,
            Self::LocalCli | Self::SystemHeartbeat | Self::HumanApproved { .. } => {
                TrustZone::ControlPlane
            }
            Self::AgentGenerated { .. } => TrustZone::AgentRuntime,
        }
    }

    /// Whether this origin came through a bridge (external, untrusted ingress).
    #[must_use]
    pub fn is_bridge(&self) -> bool {
        matches!(self, Self::BridgeTelegram { .. } | Self::BridgeSlack { .. })
    }

    /// Whether this origin is local (CLI or system).
    #[must_use]
    pub fn is_local(&self) -> bool {
        matches!(self, Self::LocalCli | Self::SystemHeartbeat)
    }

    /// Extract the typed platform identity for per-user config lookups
    /// (tier ceiling overrides, etc.). Returns `None` for non-bridge origins.
    #[must_use]
    pub fn platform_identity(&self) -> Option<PlatformIdentity> {
        match self {
            Self::BridgeTelegram { user_id } => Some(PlatformIdentity::Telegram {
                user_id: user_id.clone(),
            }),
            Self::BridgeSlack { user_id, .. } => Some(PlatformIdentity::Slack {
                user_id: user_id.clone(),
            }),
            Self::LocalCli
            | Self::AgentGenerated { .. }
            | Self::SystemHeartbeat
            | Self::HumanApproved { .. } => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bridge_origins_are_ingress_zone() {
        let slack = ActionOrigin::BridgeSlack {
            user_id: "U123".into(),
            channel_id: "C456".into(),
        };
        assert_eq!(slack.trust_zone(), TrustZone::Ingress);
        assert!(slack.is_bridge());
        assert!(!slack.is_local());
    }

    #[test]
    fn cli_origin_is_control_plane() {
        assert_eq!(ActionOrigin::LocalCli.trust_zone(), TrustZone::ControlPlane);
        assert!(ActionOrigin::LocalCli.is_local());
    }

    #[test]
    fn agent_origin_is_runtime_zone() {
        let agent = ActionOrigin::AgentGenerated {
            session_id: SessionId::new(),
        };
        assert_eq!(agent.trust_zone(), TrustZone::AgentRuntime);
    }

    #[test]
    fn human_approved_preserves_original_origin() {
        let original = ActionOrigin::BridgeSlack {
            user_id: "U123".into(),
            channel_id: "C456".into(),
        };
        let approved = ActionOrigin::HumanApproved {
            approver: "sebastian".into(),
            original_origin: Box::new(original.clone()),
        };
        // HumanApproved elevates to control plane
        assert_eq!(approved.trust_zone(), TrustZone::ControlPlane);
    }
}
